import "./globals.css";
import Bunner from "./module/components/bunner";
import Menu from "./module/components/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <Bunner/>
        <Menu />
        {children}
        <p>Footer</p>
      </body>
    </html>
  );
}
